services:
  db-lelu-seven:
    image: postgres:15
    environment:
      POSTGRES_DB: lelu_seven_finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api-lululele-finance:
    build: .
    depends_on:
      db-lelu-seven:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - JWT_SECRET=82d9c33fa41d1d0f03c3ed6df804065fb72abc8889ef4ba42c982ca3d73f6c24
    env_file:
      - .env
volumes:
  pgdata: