spring.application.name=lululele

spring.datasource.url=jdbc:postgresql://localhost:5432/sisvigia?currentSchema=seguranca
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=p0hAmehHGcRVNNUTmlK8RT7nHfwAKzzHxMicPlZHuFU
jwt.expiration=3600
jwt.refresh-expiration=864000